### ISSUE TITLE
Add readme.md/contributing/license to this repo

### ISSUE THREAD

**Issue by Eilon** [aspnet/WebListener#228]

**Comment by Eilon** [comment]
Travis enabled.
AppVeyor enabled, key = 413hlt87c3p24on8

**Comment by Eilon** [comment]
Oops, didn't mean to close this.

**Comment by Tratcher** [comment]
Travis? WebListener shouldn't be added to travis, it's Windows only.

**Comment by Eilon** [comment]
I added both. Can this not even build when not running on Windows? I know nothing will run, but I would think it could build, no?

**Comment by Tratcher** [comment]
It could build, but then it would try to run the tests and explode. Why build if you can't test? Just because Travis is more reliable than AppVeyor?
