### ISSUE TITLE
Check Identity.AuthenticationType usages in WebListener 

### ISSUE THREAD

**Issue by pakrym** [aspnet/WebListener#266]
See: https://github.com/aspnet/IISIntegration/issues/231

**Comment by muratg** [comment]
@pakrym could you do a quick check?

**Comment by pakrym** [comment]
I have verified that scenario from IISIntegration issues successfully authenticates going though code path that hits `identity.AuthenticationType` when running WebListener as different local user.

**Comment by muratg** [comment]
👍
