### ISSUE TITLE
Update hosting dependency to 1.0.1

### ISSUE THREAD

**Issue by Tratcher** [aspnet/WebListener#274]
https://github.com/aspnet/Hosting/issues/873

**Comment by muratg** [comment]
@JunTaoLuo were you planning to do this?

**Comment by JunTaoLuo** [comment]
Yea I'll take care of it while updating all of our repos for 1.0.3 patch. I'm assuming the tag should be changed to patch-approved?

**Comment by JunTaoLuo** [comment]
This is done in https://github.com/aspnet/WebListener/commit/d3b18542b18e30e36cec9d59162a1f41bccfc36b
