### ISSUE TITLE
HTTP Error 503. The service is unavailable.

### ISSUE THREAD

**Issue by timomta** [aspnet/WebListener#276]
Hello, I've set up a Server Core 2016 machine with .Net core installed on it. I have reserved the urls `http://*:80` and `https://*:443`, installed an ssl cert, and associated it with the https url.

When I use the code from Getting Started (https://docs.asp.net/en/latest/getting-started.html), I am able to get the expected Hello message from ASP.Net core using Kestrel. However, when I change to WebListener, I receive an HTTP Error 503, service unavailable error from the server. Here is my code (I only changed Program.cs and project.json, startup.cs is the same as the getting-started tutorial):

**Program.cs**:
```
using System;
using Microsoft.AspNetCore.Hosting;

namespace aspnetcoreapp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseWebListener()
		.UseUrls("http://*:80", "https://*:443")
                .UseStartup<Startup>()
                .Build();

            host.Run();
        }
    }
}
```
**Project.json**:
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {},
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        },
        "Microsoft.AspNetCore.Server.WebListener": "1.0.0"
      },
      "imports": "dnxcore50"
    }
  }
}
```
Any ideas why WebListener will not respond and Kestrel will?

**Comment by timomta** [comment]
Hmm, the star character is special and does not show up. The urls were supposed to be http://<star>:80 and https://<star>:443 in the code and text of the last message.

**Comment by Tratcher** [comment]
What console output do you get when you run it?

**Comment by timomta** [comment]
Hi Chris,

Here is a shot of the console currently:

C:\hwapp>dotnet run
Project hwapp (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling hwapp for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:02.8963508


Hosting environment: Production
Content root path: C:\hwapp\bin\Debug\netcoreapp1.0
Now listening on: http://*:80
Now listening on: https://*:443
Application started. Press Ctrl+C to shut down.

**Comment by Tratcher** [comment]
I've seen this happen when the netsh reservations do not exactly match the UseUrls values.
http://stackoverflow.com/questions/22293445/http-503-service-is-unavailable-when-trying-to-browse-signalr-hubs/22972905#22972905

This can also happen if there is another more specific registration for that port like `http://mydomain:80/`. * is considered a weak wildcard, it only matches if nothing else matched first. You can try a strong wildcard instead to make sure you have exclusive access to that port. `http://+:80/`
https://msdn.microsoft.com/en-us/library/windows/desktop/aa364698(v=vs.85).aspx

**Comment by timomta** [comment]
I checked the reservations with netsh http show urlacl, and I had created them with a strong wildcard.
I changed the code to match the reservations: .UseUrls("http://+:80", "https://+:443")
WebListener properly responds to requests now! Thanks!
For whatever reason Kestrel worked with the weak wildcard.

**Comment by Tratcher** [comment]
Kestrel does not use netsh/http.sys. The HTTPS setup instructions for Kestrel are very different.

**Comment by juniormayhe** [comment]
Sometimes it is just about application pool that has been stopped
