### ISSUE TITLE
Is there going to be an official OWIN host?

### ISSUE THREAD

**Issue by NimaAra** [aspnet/WebListener#282]
There is already the [OwinWebListener](https://github.com/damianh/OwinWebListenerHost) but is there a plan to have an official _Microsoft.Owin.Host.WebListener_ similar to _Microsoft.Owin.Host.HttpListener_ for those of us who are not ready to move to _ASP .NET Core_?

**Comment by davidfowl** [comment]
Nope. 

https://blogs.msdn.microsoft.com/webdev/2014/11/14/katana-asp-net-5-and-bridging-the-gap/

That said, it should be trivial to write one based on the older HttpListener implementation but it's not something we're going to maintain.

**Comment by davidfowl** [comment]
Oh wait @damianh did it already! OSS FTW 😄

**Comment by damianh** [comment]
But it's not official! ;)

**Comment by NimaAra** [comment]
@davidfowl That link is very helpful, interesting how I missed that despite following up every single one of ASP.Net stand-ups! 

@damianh Thanks for the library, I was mainly concerned about the rate of allocation in your library but then after benchmarking didn't notice much difference. So we will start using that. :-)

**Comment by damianh** [comment]
@NimaAra, I won't claim the lib is mine. It is a fork of the HttpListenerHost so if any warts there it's safe to say they have been forked too ;)

I created this for the same reasons you mentioned.

I also fully respect @davidfowl's position that the aspnet teams' focus means this is not something they want to do. So OSS FTW indeed :)

I will of course take PRs for any improvements, I expect I will be using and maintaining this for some time.

**Comment by NimaAra** [comment]
@damianh Okay, that is great, I shall let you know if we come across anything we could improve. Thanks.
