### ISSUE TITLE
Client certificate authentication

### ISSUE THREAD

**Issue by jpmnteiro** [aspnet/WebListener#285]
Hey,

Setting up a couple of test projects using Kestrel and WebListener using HTTPS and client certificate authentication.  I've managed to do both parts using Kestrel, but I can't seem find a way or any literature of how to do the client certificate authentication part using WebListener.

So, is it possible at all and if it is, is there an example somewhere?

**Comment by Tratcher** [comment]
Can you show what you did for Kestrel? That should help us understand what you're trying to achieve with WebListener.

**Comment by jpmnteiro** [comment]
@Tratcher thank you for the reply, here's the Kestrel code:

```
[...].UseKestrel(options =>
                {
                    var httpsOptions = new HttpsConnectionFilterOptions
                        {
                            SslProtocols = SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12,
                            ClientCertificateMode = ClientCertificateMode.RequireCertificate,
                            CheckCertificateRevocation = true,
                            ServerCertificate = GetCert(),
                            ClientCertificateValidation = (certificate2, chain, arg3) => true // for testing purposes only
                        };
                                                                  
                    options.UseHttps(httpsOptions);
                });
```

**Comment by jpmnteiro** [comment]
@Tratcher I managed to get it working. Given that WebListener requires the SSL certificate to be bond using `netsh`, it was a matter of setting `clientcertnegotiation` to `enable` when adding the SSL certificate to the port. 

So, much like SSL, it's not something that concerns WebListener directly, but rather Http.sys

For anyone who may come across this in the future:

`netsh http add sslcert ipport=0.0.0.0:[port] certhash=[thumbprint] appid=[guid] clientcertnegotiation=enable`

And yes, you can get a hold of the client certificate via the `GetClientCertificateAsync()`.
